# Generated by Django 4.0.2 on 2022-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/c/HiteshChoudharydotcom', max_length=255),
            preserve_default=False,
        ),
    ]
