# Generated by Django 4.0.2 on 2022-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtuber_camera_type_alter_youtuber_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='video_url',
            field=models.CharField(max_length=255),
        ),
    ]
